### ISSUE TITLE
Merging commits with Brackets-Cont

### ISSUE THREAD

**Issue by ScanuNicco** [quadre-code/quadre#249]
Brackets-Cont is a community project focused on continuing the development of Brackets now that Adobe is no longer maintaining it. We are considering moving the project to electron to make it easier to build an maintain, and I was wondering if you would be willing to help with the transition. It is currently being discussed on our discord server and on this issue: https://github.com/brackets-cont/brackets/issues/26

**Comment by abose** [comment]
Hi @ficristo 
Adding to @ScanuNicco It would help the brackets community a lot if you are willing to take a maintainer role in the community and help with building brackets.next :)

**Comment by ficristo** [comment]
Hi @ScanuNicco @abose 
I think I need to clarify \ emphasize some things.
[Quadre](https://github.com/quadre-code/quadre) is a fork of [Brackets-Electron](https://github.com/brackets-userland/brackets-electron): so all the hard work to port Brackets to use Electron was **NOT** done by me.
And it still doesn't contains all changes made in Brackets, so there are some api that aren't implemented in Quadre. Especially in the shell side.

My idea with Quadre was to experiment with it in different directions. For example off the top of my head:
- move to Gulp instead of Grunt for the build system
- use Typescript instead of plain Javascript
- run tests on CI (travis \ appveyor)
- use ESLint more (thorugh https://github.com/ficristo/eslint-moody)
- use a custom addon to implement some changes to how comment code works (through https://github.com/ficristo/codemirror-addon-toggle-comment)

I've partially done some of these but others things remained only in my head.

Quadre was and still is, from time to time, a toy project of mine so I'm not sure if it really is something you want to merge fully.
I doubt all the changes i did are something you want.
Feel free to poke at it or ask questions if you like. It's MIT licensed, like Brackets was, so you can merge or cherry pick what you want.

While mildly interested I'm not really motivated to take a maintainer role.

**Comment by abose** [comment]
Thanks for the insights on Quadre-code @ficristo . Hopefully, we should be able to use some part of quadre when we transition to electron in brackets.
